export const mealActionTypes = {
  UPDATE_MEAL_REQUEST: "UPDATE_MEAL_REQUEST",
  UPDATE_MEAL_SUCCESS: "UPDATE_MEAL_SUCCESS",
  UPDATE_MEAL_FAILURE: "UPDATE_MEAL_FAILURE",
  GET_MEALS_REQUEST: "GET_MEALS_REQUEST",
  GET_MEALS_SUCCESS: "GET_MEALS_SUCCESS",
  GET_MEALS_FAILURE: "GET_MEALS_FAILURE",
  DELETE_MEAL_REQUEST: "DELETE_MEAL_REQUEST",
  DELETE_MEAL_SUCCESS: "DELETE_MEAL_SUCCESS",
  DELETE_MEAL_FAILURE: "DELETE_MEAL_FAILURE",
  RESET_MESSAGE: "RESET_MESSAGE",
};
