export const signupActionTypes = {
    SIGNUP_USER_REQUEST: "SIGNUP_USER_REQUEST",
    SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
    SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
    RESET_MESSAGE: "RESET_MESSAGE",
  };
  